### PR TITLE
allow user four new options

### PR DESCRIPTION
**Pull request by arichnad**
1. allow user to quiet output.
2. allow user to override max_value.
3. allow the user to override the gradient. 
4. allow the user to skip input points.

I can separate these into different pull requests if you'd like (just let me know which things you want and don't want).

### CODE REVIEW

**Comment by arichnad** [comment]
Any thoughts on this pull request?  I can separate these into different pull requests if you'd like.  Thanks!

**Comment by remisalmon** [comment]
Thanks for the PR, I plan to have an option for a light background map with a different colormap, would make sense to use the blue-red one for that.

What is the use of --skip-ratio?

**Comment by arichnad** [comment]
> --skip-ratio

Well we can call it something else, or come up with a smarter solution, but here's my situation:

I have a lot of gpx-file inputs and my output html is getting a little BIG.  I'd like to make it smaller, and the simplest solution I could think of was skipping every other point.  Or use every third point, that sort of thing.

(Another more complicated solution would be to combine points that are near each-other into weighted points?)

If you'd like, I can submit the PR without skip-ratio!

**Comment by remisalmon** [comment]
The best way to reduce the # of points would be to use https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm but the skip ratio works too. Just merged it, thanks!

**Pull request merged**
